from pathlib import Path

BASE_DIR = Path(__file__).parent
TOR_BIN = BASE_DIR / "tor.exe"
PEERS_FILE = BASE_DIR / "peers.txt"
GENESIS_FILE = BASE_DIR / "genesis.json"
DATA_DIR = BASE_DIR / "data"

INTERNAL_PORT = 8090
SOCKS_PORT = 9050

DIFFICULTY = 6
MIN_DIFFICULTY = DIFFICULTY
MAX_DIFFICULTY = 34
TARGET_BLOCK_TIME = 60
RETARGET_INTERVAL = 10
REWARD = 100.0
SYNC_INTERVAL = 20